### ISSUE TITLE
Add customPaging callback

### ISSUE THREAD

**Issue by FlowinBeatz** [heimrichhannot/contao-slick#1]
Is it possible to add a config field for the "customPaging" callback?
I need a custom Paging as seen here: http://stackoverflow.com/questions/25847297/slick-js-get-current-and-total-slides-ie-3-5
As the initial JS comes directly from the extension, I don't see a change to modify the output.
Thanks a lot!

**Comment by fatcrobat** [comment]
I will try to add a simple text field, where you can add the name of your global javascript callback function.

**Comment by FlowinBeatz** [comment]
This would be really nice.
Could you also add the "unslick" setting to the slider config, so that it can be used within the breakpoint settings?

**Comment by FlowinBeatz** [comment]
BTW: Will you add the extension to the Contao Ext Repository? Slick is so much better than the currently popular "CarouFredSel" Slider, it would be a real improvement.

**Comment by fatcrobat** [comment]
Its already available via packagist, so you can install it inside the composer extension (best way to stay up 2 date). As far as i know, the contao ext repository is no longer maintained, or am i wrong?
You are very invited, create pull requests. :)

**Comment by fatcrobat** [comment]
Added with 1.0.3

**Comment by FlowinBeatz** [comment]
Unfortunately, the HTML will not be pasted into the JS, also some characters are encoded to HTML Entities:

`function(slick,index) {    return '<a>' + index + '</a>'; }`
becomes
`function&#40;slick,index&#41; {     return '' + index + ''; }`

**Comment by fatcrobat** [comment]
Please try an global function callback, like the following:

Enter in the customPaging field the following:

```
Test.customPaging
```

than create a global variable called Test, where your function can be called like the following:

```
(function($){

Test = {

   customPaging : function(slick,index){
     return '<a>' + index + '</a>';
  }
}

})(jQuery);
```

I tried to make it more reusable, writing js functions in php code, does not work very well with json_encode, cause functions and objects are escaped as string by default. 

Hope that helps.

**Comment by FlowinBeatz** [comment]
That worked like a charme! But it should be documented somewhere, or you don't get that clue by yourself ;-)
Maybe I can contribute with some translations or documentations?

**Comment by fatcrobat** [comment]
You are very welcome to pull requests. :) I am bit short on time right now, as long as i am working on customer projects. But slick will be the way to go for us as company.
