### ISSUE TITLE
Keine Responsivität gegeben

### ISSUE THREAD

**Issue by FlowinBeatz** [heimrichhannot/contao-slick#10]
Der Slider ist in Contao nicht responsiv, da die Berechnung der Breite des Sliders aus irgendeinem Grund fehlschlägt.

<div class="slick-track" style="opacity: 1; width: 15000px; left: -2880px;" role="listbox"><div class="ce_slick-slide-separator block slick-slide slick-cloned" data-slick-index="-1" aria-hidden="true" tabindex="-1">

Der Slide enthält ein 2880px breites Bild, die Breite des gesamten "slide-track" ist kurioserweise aber immer auf 15000px, egal welcher Inhalt eingebunden ist. Die "left: -2880px;" sind dann aber wieder richtig berechnet (habe es auch mit 300px großen Bildern getestet).

Außerdem fällt im Vergleich zu einem Vanilla Slick auf, dass die slick-slide Klasse keine Inline-Breite bekommt: 

Contao Slick: <div class="ce_slick-slide-separator slick-slide" data-slick-index="0" aria-hidden="false" tabindex="-1" role="option" aria-describedby="slick-slide00">

Vanilla Slick: <div class="ce_image block slick-slide slick-current slick-active" data-slick-index="0" aria-hidden="false" style="width: 1130px;" tabindex="-1" role="option" aria-describedby="slick-slide00">

Woran kann das liegen?

**Comment by FlowinBeatz** [comment]
Problem sitzt auf dem Bürostuhl, bzw. in der Beschreibung der "variableWidth" Einstellung. "Automatische Slide-Breiten-Berechnung deaktvieren. Standard: false" Mit dem Ankreuzen der Einstellung habe ich genau dies also deaktiviert, statt aktiviert. Bei der adaptiveHeight ganz oben in der Konfiguration ist es genau andersherum. Das verwirrt. Vielleicht könnt ihr das noch intuitiver machen?

**Comment by fatcrobat** [comment]
Die Slick Config basiert 1zu1 auf den Slick.js defaults/parametern. Wir haben die Beschreibung genau übernommen um keine Verwirrung zwischen slick.js doku und contao-slick aufkommen zu lassen. Der Slick-Slider ist sehr umfangreich und komplex und richtet sich besonders im Bezug auf die Konfiguration im Contao Backend an Experten bzw setzt ein Maß an Grundwissen über die slick Konfiguration voraus. Ein pull request ist dennoch immer gern gesehen, sofern er zur Vereinfachung beiträgt.

Grüße
