### ISSUE TITLE
Compatibility to Contao 4.1

### ISSUE THREAD

**Issue by christianromeni** [heimrichhannot/contao-slick#11]
Is it possible to add Contao 4.1 compatibility?
Its currently not working.

**Comment by fatcrobat** [comment]
Hi, 

we currently do not support contao 4, as it does not provide LTS support. We tried to install slick under contao 4.1 and at this point it wont work properly, cause the multicolumnwizard dependeny (breakpoint configuration) does not work at all. 

We will move from multicolumnwizard to contao-fieldpalette in contao 3 soon, and if we can provide a backwards-compatibility, we will provide a contao 4 version of slick slider.

Thanks for your response.

**Comment by fatcrobat** [comment]
Closed, slick is now working with contao 4.x
