### ISSUE TITLE
Optionen eingeben

### ISSUE THREAD

**Issue by Thoni** [heimrichhannot/contao-slick#12]
Hallo,

ich wollte den Slider 'Variable Width' einsetzen.

>   'dots': true,
>   'infinite': true,
>   'slidesToShow': 1,
>   'centerMode': true,
>   'variableWidth': true,
>   

Wo muss man die Optionen eingeben?

**Comment by fatcrobat** [comment]
Im Backens von Contao gibt es den Menüpunkt "Slick-Konfigurationen" dort kann für jeden slider eine individuelle Konfiguration erstellt und dann am entsprechenden Slider hinterlegt werden. Dort gibt es auch den Punk variableWidth.
