### ISSUE TITLE
slick gallery in news -> error

### ISSUE THREAD

**Issue by reluem** [heimrichhannot/contao-slick#14]
Hi, 

I have a question regarding the slick backend integration.
When I click on add gallery in a news article,  Contao activates the add gallery and fails to load the slick palette apparently (with this error):

> [29-Jan-2017 13:01:20 Europe/Berlin] PHP Fatal error: Uncaught exception 'Error' with message 'Class 'tl_content' not found' thrown in /is/htdocs/xxx/www/xxx/system/modules/core/library/Contao/System.php on line 140
> #0 system/modules/core/drivers/DC_Table.php(1929): Contao\System->import('tl_content')
> #1 system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
> #2 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('news')
> #3 contao/main.php(20): Contao\BackendMain->run()

I am wondering, however, why this "Add gallery" even exists. I thought that the add gallery functionality for news elements has generally been abolished with Contao 3 (e.g. [here](https://contao.org/de/erweiterungsliste/view/newsgallery.10000069.de.html)).

I initally though that I still had some old tables, but the 'Add gallery' column in tl_news is generated by slick!

Thanks for your help!

**Comment by fatcrobat** [comment]
Sorry for the late response, we were quiet busy.

Slick provides a gallery on tl_news entities. This is a feature and works as intended. For example you want to display a gallery for a given news in another region (stage for example) as the news content itself. The gallery must be attached to the news entity, instead of tl_content, otherwise you don't know what gallery within tl_content you should display.

What contao version and slick versiokn you are using? With contao 3.5.x and slick 1.3.5 there does no error occur.

**Comment by reluem** [comment]
okay, understood & seems reasonable.

Issue persists on Contao 3.5.24 with PHP 7 (maybe there is some problem with v7?)
Right after clicking on 'add gallery' in a news entry, the error occurs.

**Comment by fatcrobat** [comment]
Updated slick to support php7, can you please try the latest version?

**Comment by reluem** [comment]
yes, completely removed the package and reinstalled to latest. Still the same error!

Updated error message:

> [21-Apr-2017 07:18:11 Europe/Berlin] 
> PHP Warning: in_array() expects parameter 2 to be array, null given in /is/htdocs/xxx/www/xxx/system/modules/core/library/Contao/System.php on line 140
> #0 [internal function]: __error_enhanced(2, 'in_array() expects parameter 2 to be array, null given', 'system/modules/core/library/Contao/System.php', 140, Array)
> #1 system/modules/core/library/Contao/System.php(140): in_array('getInstance', NULL)
> #2 system/modules/core/drivers/DC_Table.php(1929): Contao\System->import('tl_content')
> #3 system/modules/core/classes/Ajax.php(426): Contao\DC_Table->edit(false, 'sub_addGallery')
> #4 system/modules/core/classes/Backend.php(414): Contao\Ajax->executePostActions(Contao\DC_Table)
> #5 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('news')
> #6 contao/main.php(20): Contao\BackendMain->run()
> 
> 
> [21-Apr-2017 07:18:11 Europe/Berlin] PHP Fatal error: Uncaught exception 'Error' with message 'Class 'tl_content' not found' thrown in /is/htdocs/xxx/www/xxx/system/modules/core/library/Contao/System.php on line 140
> #0 system/modules/core/drivers/DC_Table.php(1929): Contao\System->import('tl_content')
> #1 system/modules/core/classes/Ajax.php(426): Contao\DC_Table->edit(false, 'sub_addGallery')
> #2 system/modules/core/classes/Backend.php(414): Contao\Ajax->executePostActions(Contao\DC_Table)
> #3 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('news')
> #4 contao/main.php(20): Contao\BackendMain->run()

**Comment by fatcrobat** [comment]
Cant reproduce, as you can see in the screenshot below, addGallery does not throw any exceptions. 

![addgallery](https://user-images.githubusercontent.com/480054/28354303-b746adc2-6c5f-11e7-830b-566242c108d7.png)

**Comment by fatcrobat** [comment]
@reluem Could finally reproduce the issue under php 7.1 and contao 4.4, and fixed it in `1.4.1`.

**Comment by moyen03** [comment]
Hi @fatcrobat I am completely new in Contao and I am also facing the above issue with contao 3.5, PHP 7.1 and slick 1.8.0. Any help ?

Warning: in_array() expects parameter 2 to be array, null given in system/modules/core/library/Contao/System.php on line 140
#0 [internal function]: __error(2, 'in_array() expe...', 's...', 140, Array)
#1 system/modules/core/library/Contao/System.php(140): in_array('getInstance', NULL)
#2 system/modules/core/drivers/DC_Table.php(1929): Contao\System->import('tl_content')
#3 system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#4 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('news')
#5 contao/main.php(20): Contao\BackendMain->run()
#6 {main}

Fatal error: Uncaught exception Error with message Class 'tl_content' not found thrown in system/modules/core/library/Contao/System.php on line 140
#0 system/modules/core/drivers/DC_Table.php(1929): Contao\System->import('tl_content')
#1 system/modules/core/classes/Backend.php(650): Contao\DC_Table->edit()
#2 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('news')
#3 contao/main.php(20): Contao\BackendMain->run()
#4 {main}
