### ISSUE TITLE
Slider Syncing

### ISSUE THREAD

**Issue by nicklasmatt** [heimrichhannot/contao-slick#16]
Hallo,
ich möchte gerne Slider Syncing mit dem Contao Plugin umsetzen. Die Einstellungen zu den beiden Slider Konfigurationen habe ich aus der Dokumentation zu Slider Syncing (http://kenwheeler.github.io/slick/) übernommen. Im fertigen JS wird allerdings bei beiden Slider "asNavFor" mit "null" ausgegeben.
Gibt es vielleicht ein Howto, wie die beiden Slider in Contao angelegt werden müssen, um sich gegenseitig zu synchronisieren?

**Comment by fatcrobat** [comment]
Hi,

hast du in der Slick Konfiguration im Backend beim Dropdown des Navigationsslider, den entsprechenden Slider ausgewählt? Stell bitte 2 Screenshots der beiden Konfigurationen hier ein. 'assets/js' Ordner gern nochmal leeren.

**Comment by nicklasmatt** [comment]
Hi,
hier Screenshots von den Konfigurationen und ein Screenshot der neu angelegten JS-Datei.
Das assets-Verzeichnis habe ich zuvor geleert. Reicht der Screenshot der Konfigurationen oder brauchst du gesamte Seite?
![bildschirmfoto 2017-07-18 um 08 36 51](https://user-images.githubusercontent.com/30229652/28303636-70d8c0c6-6b94-11e7-9798-871a19706dda.png)
![bildschirmfoto 2017-07-18 um 08 37 09](https://user-images.githubusercontent.com/30229652/28303635-70d89506-6b94-11e7-90ad-884b2052075c.png)
![bildschirmfoto 2017-07-18 um 08 37 24](https://user-images.githubusercontent.com/30229652/28303637-70e2f67c-6b94-11e7-8bcd-afa5134d50fa.png)

**Comment by fatcrobat** [comment]
Fixed in 1.3.10.

**Comment by nicklasmatt** [comment]
Vielen Dank! Funktioniert jetzt wie gewünscht.
