### ISSUE TITLE
contao 4.42  - Datenbank Fehler nach contao-slick-Installation

### ISSUE THREAD

**Issue by b-fender** [heimrichhannot/contao-slick#17]
Hi!
gerade ist mir aufgefallen, dass nach der Installation in Contao 4.4.2
(mit composer require) nach dem Datenbank-Update folgendes übrigbleibt, das auch nicht auzulösen ist:

ALTER TABLE tl_slick_config CHANGE slick_edgeFriction slick_edgeFriction DOUBLE PRECISION DEFAULT '0.00' NOT NULL

Fehler ist eventuell doppeltes: " ... slick_edgeFriction slick_edgeFriction... " in SQL s.o.

**Comment by fatcrobat** [comment]
Can`t reproduce on contao 4.4.2 width slick 1.3.11. What MySQL Version you are running on?

```
'sql'       => "float(9,2) unsigned NOT NULL default '0.00'",
```
Did not change anything on the `slick_edgeFriction` SQL in the recent versions.

**Comment by b-fender** [comment]
5.5.55-0+deb8u1 - (Debian)  
i have the same error in 2 installations.
Contao Install-Tool shows:
ALTER TABLE tl_slick_config CHANGE slick_edgeFriction slick_edgeFriction DOUBLE PRECISION DEFAULT '0.00' NOT NULL
selecting this in Contao Install-Tool and clicking on 'Update Database'
does not do anything.
![contao-install](https://user-images.githubusercontent.com/1473692/28666481-c9247b64-72c7-11e7-9ba5-229471b13f9e.jpg)

**Comment by fatcrobat** [comment]
We are running Contao 4.4.2 on MySQL 5.7.19 without this behavior. The sql syntax is correct, maybe there is an problem between yor sql version and contaos DCAExtractor. Can you please try the following sql:

'sql'                 =>  "decimal(9,2) NOT NULL default '0.00'"

in dca/tl_slick_spread.php?

**Comment by b-fender** [comment]
Yes and Thanks! With the new sql, contao updates the database correctly!

**Comment by fatcrobat** [comment]
Pull request welcome, i am off for vacation.
