### ISSUE TITLE
Warning: Invalid argument supplied for foreach()  | Contao 4.4.2, contao-slick 1.4.2

### ISSUE THREAD

**Issue by hostis912** [heimrichhannot/contao-slick#18]
Hello, after updating to Contao 4.4.2 and Contao-Slick 1.4.2, getting multiple warnings on each site:

`Warning: Invalid argument supplied for foreach() in /var/www/vhosts/.../vendor/heimrichhannot/contao-slick/classes/SlickConfig.php on line 228`

**Comment by fatcrobat** [comment]
Fixed in 1.4.3
