### ISSUE TITLE
Column not found: 1054 Unknown column 'slickgalleryTpl' in 'field list'

### ISSUE THREAD

**Issue by Thoni** [heimrichhannot/contao-slick#19]
Hallo,
im Contao 4.4.2 (Composer-Installation) kommt diese Fehlermeldung, sobald ich in einem Artikel ein Contentelement hinzufügen möchte:

INSERT INTO tl_content (type, slickgalleryTpl, ...
... Column not found: 1054 Unknown column 'slickgalleryTpl' in 'field list'

In der entsprechenden Tabelle tl_content wird auch nur diese Spalte hinzugefügt: slickContentSlider

In der tl_slick_spread.php steht das 
`
        'slickgalleryTpl'        => [
            'label'            => &$GLOBALS['TL_LANG']['tl_content']['galleryTpl'],`
... dort steht es auch in den palettes und subpalettes

Viele Grüße
Thoni

**Comment by fatcrobat** [comment]
Kannst du bitte deinen lokalen Cache leeren? Prod und Dev. Die Felder sollten alle korrekt verfügbar sein.

**Comment by Thoni** [comment]
Leider hat es nicht geholfen.
Auch ein Update brachte nichts.

Ist es denn richtig, dass das in der tl_slick_spread.php und nicht in der tl_content.php stehen muss:



>         'slickgalleryTpl'        => [
>             'label'            => &$GLOBALS['TL_LANG']['tl_content']['galleryTpl'],
>             'exclude'          => true,
>             'inputType'        => 'select',
>             'default'          => 'slick_default',
>             'options_callback' => ['tl_slick_spread', 'getGalleryTemplates'],
>             'eval'             => ['tl_class' => 'w50'],
>             'sql'              => "varchar(64) NOT NULL default ''",
>         ],



Die Fehlermeldung erwartet die Spalte in der tl_content.

Viele Grüße
Thoni

**Comment by Thoni** [comment]
Hier ist dazu der Log-Eintrag:

>  [2017-09-01 08:03:30] app.CRITICAL: An exception occurred. {"exception":"[object]
> (Doctrine\\DBAL\\Exception\\InvalidFieldNameException(code: 0): An exception
> occurred while executing 'INSERT INTO tl_content (type, slickgalleryTpl,
> floating, sortOrder, perRow, sliderStartSlide, com_order, com_template, pid,
> sorting, ptable, tstamp) VALUES ('text', 'slick_default', 'above', 'ascending',
> 4, 0, 'ascending', 'com_default', 3, 256, 'tl_article', 0)':\n\nSQLSTATE[42S22]:
> Column not found: 1054 Unknown column 'slickgalleryTpl' in 'field list' at 
> /www/htdocs/test/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:71,
> Doctrine\\DBAL\\Driver\\PDOException(code: 42S22): SQLSTATE[42S22]: Column not found:
> 1054 Unknown column 'slickgalleryTpl' in 'field list' at 
> /www/htdocs/test/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:106,
> PDOException(code: 42S22): SQLSTATE[42S22]: Column not found: 1054 Unknown column
> 'slickgalleryTpl' in 'field list' at 
> /www/htdocs/test/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:104)"} []

In deinem Quelltext steht meiner Meinung nach nichts, was den Fehler auslösen kann.
... aber er ist leider da.

Viele Grüße
Thoni

**Comment by fritzmg** [comment]
The slick extension injects additional Fields via a [loadDataContainer Hook](https://github.com/heimrichhannot/contao-slick/blob/1.4.9/classes/Hooks.php#L65-L174) into [supported tables, which includes `tl_content`](https://github.com/heimrichhannot/contao-slick/blob/1.4.9/config/config.php#L32-L34).

@Thoni you should open the Install Tool via `app_dev.php/contao/install` and then post the full stack trace here.

**Comment by Thoni** [comment]
Ich habe app_dev.php/contao/install und dann das Install-Tool nochmal aufgerufen und nun wurden zwei Felder hinzugefügt.
Jetzt scheint es zu funktionieren.

Danke

**Comment by Thoni** [comment]
Jetzt möchte das Installtool wieder zwei Spalten löschen:

Wenn ich das mache, gibt es wieder die Fehlermeldung, also mache ich es nicht.

Warum bringt die Erweiterung das Installtool durcheinander?

**Comment by fatcrobat** [comment]
@Thoni Was passiert, wenn du bevor du das install-tool aufrufst den ordner var/cache löschts?

**Comment by sebssch** [comment]
Bei mir möchte das Modul immer Spalten löschen. Anschließend wirft es einen Fehler. Nach Manuellem erneutem anlegen in der Datenbank Funktioniert alles wieder mit Ausnahme, dass es die Spalten über das InstallTool wieder löschen möchte...
![contao open source cms 2017-11-07 16-53-25](https://user-images.githubusercontent.com/18069290/32502998-690a1f20-c3dc-11e7-80a5-471c8f993050.png)

**Comment by tblumrich** [comment]
Hallo.
Ich habe das Problem ebenfalls. Contao 4.4.7 und folgende Fehlermeldung passiert wenn ich ein neues Inhaltselement anlegen will:
`An exception occurred while executing 'INSERT INTO tl_content (type, slickgalleryTpl, floating, sortOrder, perRow, sliderStartSlide, com_order, com_template, pid, sorting, ptable, tstamp) VALUES ('text', 'slick_default', 'above', 'ascending', 4, 0, 'ascending', 'com_default', 6, 256, 'tl_article', 0)': SQLSTATE[42S22]: Column not found: 1054 Unknown column 'slickgalleryTpl' in 'field list'`
Caches inkl prod hab ich mehrfach gelöscht und probiert. Den Aufruf via app_dev.php klappt nicht, es kommt:
`You are not allowed to access this file. Check app_dev.php for more information.`

Was ist zu tun?

**Comment by Thoni** [comment]
Hi,

bei mir will das Install-Tool die Spalten auch wieder löschen.
Ich ignoriere das, bis es gefixt ist.

**Comment by tblumrich** [comment]
Hi. Bei mir will das Install-Tool ja garnichts löschen. Ich installiere die Erweiterung über den Manager und aktualisiere die Datenbank über das Install-Tool. Nichts weiter. Das hab ich jetzt schon 5x gemacht...
Nur eben die o.g. Fehlermeldung beim Anlegen eines neuen Inhaltselements.
Kann das was mit der nicht Aufrufbarkeit der app_dev zu tun haben?

**Comment by tblumrich** [comment]
Ich nochmal. Nach viel Recherche ist mir nun auch klar das die app_dev den Entwickler/Debug Modus anwirft und ich dafür einen Benutzer anlegen muss (bin halt Frontendler). Das hab ich jetzt gemacht... außer einer Menge ausgegebener mir nichtssagender Fehler/Warnungen bekomme ich übers Installtool auch keine weiteren Tabellen/Spalten für die Datenbank angeboten. 
Ich hab die Erweiterung auch in einer anderen Contao Installation versucht zu installieren - das selber Ergebnis wie oben.
Kann ich das fehlende in der Datenbank den irgendwie manuell anlegen? Wenn ja, wie(genau)?

Würde mich echt über Hilfe freuen.
Thomas

**Comment by fritzmg** [comment]
> Das hab ich jetzt gemacht... außer einer Menge ausgegebener mir nichtssagender Fehler/Warnungen

Und welche Fehler sind das?

**Comment by tblumrich** [comment]
Ich kopier das mal aus dem Reiter "StackTrace"
`Symfony\Component\Debug\Exception\ContextErrorException:
Warning: DOMDocument::loadXML(): Input is not proper UTF-8, indicate encoding !
Bytes: 0xBB 0x3C 0x2F 0x74 in Entity, line: 6

  at vendor/contao/core-bundle/src/Config/Loader/XliffFileLoader.php:144
  at Contao\CoreBundle\Config\Loader\XliffFileLoader->getDomDocumentFromFile('/var/www/virtual/blucomp3/baltica-gesundheit/app/Resources/contao/languages/de/default.xlf')
     (vendor/contao/core-bundle/src/Config/Loader/XliffFileLoader.php:76)
  at Contao\CoreBundle\Config\Loader\XliffFileLoader->convertXlfToPhp('/var/www/virtual/blucomp3/baltica-gesundheit/app/Resources/contao/languages/de/default.xlf', 'de')
     (vendor/contao/core-bundle/src/Config/Loader/XliffFileLoader.php:55)
  at Contao\CoreBundle\Config\Loader\XliffFileLoader->load('/var/www/virtual/blucomp3/baltica-gesundheit/app/Resources/contao/languages/de/default.xlf', 'de')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/System.php:433)
  at Contao\System::loadLanguageFile('default')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:389)
  at Contao\DcaExtractor->createExtract()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:123)
  at Contao\DcaExtractor->__construct('tl_user_group')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/DcaExtractor.php:145)
  at Contao\DcaExtractor::getInstance('tl_user_group')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Database/Installer.php:284)
  at Contao\Database\Installer->getFromDca()
     (vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php:315)
  at Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider->getSqlDefinitions()
     (vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php:70)
  at Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider->appendToSchema(object(Schema))
     (vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php:136)
  at Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider->createSchemaFromDca()
     (vendor/contao/core-bundle/src/Doctrine/Schema/DcaSchemaProvider.php:60)
  at Contao\CoreBundle\Doctrine\Schema\DcaSchemaProvider->createSchema()
     (vendor/contao/installation-bundle/src/Database/Installer.php:104)
  at Contao\InstallationBundle\Database\Installer->compileCommands()
     (vendor/contao/installation-bundle/src/Database/Installer.php:60)
  at Contao\InstallationBundle\Database\Installer->getCommands()
     (vendor/contao/installation-bundle/src/Controller/InstallationController.php:404)
  at Contao\InstallationBundle\Controller\InstallationController->adjustDatabaseTables()
     (vendor/contao/installation-bundle/src/Controller/InstallationController.php:101)
  at Contao\InstallationBundle\Controller\InstallationController->installAction()
  at call_user_func_array(array(object(InstallationController), 'installAction'), array())
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:153)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php:68)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php:169)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (web/app_dev.php:62)`

**Comment by fritzmg** [comment]
Du hast einen Fehler in deiner `app/Resources/contao/languages/de/default.xlf`. Stelle sicher, dass die Datei mit UTF-8 enkodiert, aber __ohne__ BOM abgespeichert ist.

**Comment by tblumrich** [comment]
Okay, dankeschön. Die Datei hatte ich ganz vergessen - war mehr ein Test. Das ist jetzt gefixt.
Das o.g. Problem verbleibt allerdings... Nach Aufruf der Install über die app_dev und auch dann normal passiert nichts weiter. das Anlegen eines neuen Inhaltselements wirft o.g. Fehler.

**Comment by fatcrobat** [comment]
Das die zwei Spalten `slickgalleryTpl` und `slickConfig` in `tl_content` entfernt werden, trifft nur sehr sporadisch auf. Ich habe in der Version 1.4.14 versucht das Problem zu lokalisieren und hoffe dass die Felder nun nicht mehr gelöscht werden. Über eine Rückmeldung ob der Fehler noch auftritt wäre ich dankbar. Sofern man im "prod" Modus arbeitet, bitte den Ordner `var/cache/prod` vorher leeren/löschen.

**Comment by tblumrich** [comment]
Leider bleibts dabei. Ich hab die Erweiterung auch komplett entfernt und neu installiert. Dazwischen immer den prod cache geleert. Eine Entfernung findet m.M. nicht statt, die werden garnicht erst erstellt, wenn ich die Datenbankaktualisierung richtig interpretiere.

**Comment by fatcrobat** [comment]
Und die beiden Felder `slickgalleryTpl` und `slickConfig` existieren in der Tabell tl_content (prüfe mit phpMyAdmin) auch nicht?

**Comment by tblumrich** [comment]
Hallo.
Nein, die existieren nicht dort, nur "slickContentSlider".
Hier das was im Datenbankfenster vom Installtool drin steht beim Aktualisieren:
`CREATE TABLE tl_slick_config (
  id INT UNSIGNED AUTO_INCREMENT NOT NULL, 
  slick_accessibility CHAR(1) DEFAULT '' NOT NULL, 
  slick_adaptiveHeight CHAR(1) DEFAULT '' NOT NULL, 
  slick_arrows CHAR(1) DEFAULT '' NOT NULL, 
  slick_asNavFor INT UNSIGNED DEFAULT 0 NOT NULL, 
  slick_prevArrow VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_nextArrow VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_autoplay CHAR(1) DEFAULT '' NOT NULL, 
  slick_autoplaySpeed SMALLINT UNSIGNED DEFAULT 0 NOT NULL, 
  slick_centerMode CHAR(1) DEFAULT '' NOT NULL, 
  slick_centerPadding VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_cssEase VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_customPaging VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_dots CHAR(1) DEFAULT '' NOT NULL, 
  slick_dotsClass VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_draggable CHAR(1) DEFAULT '' NOT NULL, 
  slick_easing VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_edgeFriction NUMERIC(9, 2) DEFAULT '0.00' NOT NULL, 
  slick_fade CHAR(1) DEFAULT '' NOT NULL, 
  slick_focusOnSelect CHAR(1) DEFAULT '' NOT NULL, 
  slick_infinite CHAR(1) DEFAULT '' NOT NULL, 
  slick_initialSlide SMALLINT UNSIGNED DEFAULT 0 NOT NULL, 
  slick_lazyLoad VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_mobileFirst CHAR(1) DEFAULT '' NOT NULL, 
  slick_pauseOnHover CHAR(1) DEFAULT '' NOT NULL, 
  slick_pauseOnFocus CHAR(1) DEFAULT '' NOT NULL, 
  slick_pauseOnDotsHover CHAR(1) DEFAULT '' NOT NULL, 
  slick_respondTo VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_responsive BLOB DEFAULT NULL, 
  slick_rows SMALLINT UNSIGNED DEFAULT 1 NOT NULL, 
  slick_slide VARCHAR(255) DEFAULT '' NOT NULL, 
  slick_slidesPerRow SMALLINT UNSIGNED DEFAULT 1 NOT NULL, 
  slick_slidesToShow SMALLINT UNSIGNED DEFAULT 0 NOT NULL, 
  slick_slidesToScroll SMALLINT UNSIGNED DEFAULT 0 NOT NULL, 
  slick_speed SMALLINT UNSIGNED DEFAULT 0 NOT NULL, 
  slick_swipe CHAR(1) DEFAULT '' NOT NULL, 
  slick_swipeToSlide CHAR(1) DEFAULT '' NOT NULL, 
  slick_touchMove CHAR(1) DEFAULT '' NOT NULL, 
  slick_touchThreshold SMALLINT UNSIGNED DEFAULT 0 NOT NULL, 
  slick_useCSS CHAR(1) DEFAULT '' NOT NULL, 
  slick_useTransform CHAR(1) DEFAULT '' NOT NULL, 
  slick_variableWidth CHAR(1) DEFAULT '' NOT NULL, 
  slick_vertical CHAR(1) DEFAULT '' NOT NULL, 
  slick_verticalSwiping CHAR(1) DEFAULT '' NOT NULL, 
  slick_rtl CHAR(1) DEFAULT '' NOT NULL, 
  slick_waitForAnimate CHAR(1) DEFAULT '' NOT NULL, 
  slick_randomActive CHAR(1) DEFAULT '' NOT NULL, 
  slick_zIndex SMALLINT UNSIGNED DEFAULT 1000 NOT NULL, 
  slick_unslick CHAR(1) DEFAULT '' NOT NULL, 
  initCallback VARCHAR(255) DEFAULT '' NOT NULL, 
  afterInitCallback VARCHAR(255) DEFAULT '' NOT NULL, 
  cssClass VARCHAR(255) DEFAULT '' NOT NULL, 
  sorting INT UNSIGNED DEFAULT 0 NOT NULL, 
  tstamp INT UNSIGNED DEFAULT 0 NOT NULL, 
  title VARCHAR(255) DEFAULT '' NOT NULL, 
  PRIMARY KEY(id)
) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = MyISAM


ALTER TABLE tl_content ADD slickContentSlider VARCHAR(64) DEFAULT '' NOT NULL
ALTER TABLE tl_layout ADD inactiveComponents BLOB DEFAULT NULL
ALTER TABLE tl_layout ADD disableComponents CHAR(1) DEFAULT '' NOT NULL
ALTER TABLE tl_module ADD useSlickGallery CHAR(1) DEFAULT '1' NOT NULL
ALTER TABLE tl_module ADD slickConfig INT UNSIGNED DEFAULT 0 NOT NULL
ALTER TABLE tl_news ADD slickCustomTpl VARCHAR(64) DEFAULT '' NOT NULL
ALTER TABLE tl_news ADD slickgalleryTpl VARCHAR(64) DEFAULT '' NOT NULL
ALTER TABLE tl_news ADD slickNumberOfItems SMALLINT UNSIGNED DEFAULT 0 NOT NULL
ALTER TABLE tl_news ADD slickFullsize CHAR(1) DEFAULT '' NOT NULL
ALTER TABLE tl_news ADD slickSize VARCHAR(64) DEFAULT '' NOT NULL
ALTER TABLE tl_news ADD slickUseHomeDir CHAR(1) DEFAULT '' NOT NULL
ALTER TABLE tl_news ADD slickSortBy VARCHAR(32) DEFAULT '' NOT NULL
ALTER TABLE tl_news ADD slickOrderSRC BLOB DEFAULT NULL
ALTER TABLE tl_news ADD slickMultiSRC BLOB DEFAULT NULL
ALTER TABLE tl_news ADD addGallery CHAR(1) DEFAULT '' NOT NULL
ALTER TABLE tl_news_archive ADD slickConfig INT UNSIGNED DEFAULT 0 NOT NULL
ALTER TABLE tl_undo ADD haste_data BLOB DEFAULT NULL`

**Comment by tblumrich** [comment]
Hallo!
Bringt es irgendwas, wenn ich jemandem temporär Zugriff verschaffe zum Projekt?
LG

**Comment by fatcrobat** [comment]
Wenn es aus rechtlichen Gründen unbedenklich ist, wäre ein Datenbank Export + Projekt/composer.json inkl. Nennung der Php + Mysql Version sehr hilfreich, da wir den Fehler aktuell unter PHP7.1 + MySQL 5.5 nicht reproduzieren können.

**Comment by tblumrich** [comment]
Das rechtliche ist kein Problem. Eher das technische... ist ja doch etwas Material, ich bin kein Entwickler und kenne mich mit github nicht so aus. Ich schick dir den Kram via cloud oder E-Mail oder mach ich das irgendwie über die Plattform hier? Sorry. 
Oder ist mit Projekt nicht die ganze Contao install gemeint?

**Comment by fatcrobat** [comment]
Lads irgendwo hoch, die composer.json des contao-projekts sollte reichen und den Datenbank export, sofern alle eingesetzten module über packagist zu beziehen sind. Andernfalls brauchen wir den vendor ordner.

**Comment by tblumrich** [comment]
Hi, also hier findest du Datenbank Dump und composer.json:
https://drive.google.com/drive/folders/1ZQ4Ax97VgZ3h9CnlcTPSJPRVG4n0h3qG?usp=sharing
PHP läuft als 7.1.11, MySQL ist 5.1.73. Hoster ist Uberspace.

**Comment by fatcrobat** [comment]
Dank dir! Ich habe soeben die Datenbank eingespielt und das Projekt mit Hilfer deiner composer.json aufgesetzt. Direkt beim 1. Aufruf will er die Datenbankfelder anlegen. Wir verwenden allerdings mysql 5.7.20.

![contao open source cms](https://user-images.githubusercontent.com/480054/32721281-4202b8f4-c866-11e7-8ea2-8075a3368765.png)

**Comment by fatcrobat** [comment]
I was finally able to reproduce this issue and closed this within release 1.4.15.
