### ISSUE TITLE
Unable to add value to breakpoint set

### ISSUE THREAD

**Issue by FlowinBeatz** [heimrichhannot/contao-slick#2]
I can't find a way to add a "slick_setting" within the slick_responsive feature. Did I miss another config or is it uncompleted?

**Comment by fatcrobat** [comment]
Hi, the slick slider is still in development. We use this in most of our customer projects, so we will enhance its functionality step by step. The slick_responsive feature is available, and should be visible as shown below:

![slick konfiguration konfiguration id 13 bearbeiten - contao open source cms 3 4 1](https://cloud.githubusercontent.com/assets/480054/6057957/0c79dba6-ad23-11e4-83e8-e7108e658db0.jpg)

Add a breakpoint Pixel width as digit, and select the responsive slick config from the dropdown.
