### ISSUE TITLE
Stat failed

### ISSUE THREAD

**Issue by MicioMax** [heimrichhannot/contao-slick#20]
Hi,

I just installed the package on Contao 4.4.2.
When I create a slick config, no matter if it's used or not, I get this error :

Warning: filemtime(): stat failed for /home/massimo/Documenti/TEST_CMS/CONTAO/assets/js/slick_922ce3.js

There are no files in js folder.
When I remove the slick config with the backend I can open my website, otherwise not.

First lines of backtrace : 

`
Symfony\Component\Debug\Exception\ContextErrorException:
Warning: filemtime(): stat failed for /home/massimo/Documenti/TEST_CMS/CONTAO/assets/js/slick_922ce3.js

  at vendor/contao/core-bundle/src/Resources/contao/library/Contao/File.php:234
  at Contao\File->__get('mtime')
     (vendor/heimrichhannot/contao-slick/classes/SlickConfig.php:75)
  at HeimrichHannot\Slick\SlickConfig::doRewrite(object(SlickConfigModel), object(File), object(File), false, false)
     (vendor/heimrichhannot/contao-slick/classes/SlickConfig.php:51)
  at HeimrichHannot\Slick\SlickConfig::createConfigJs(object(SlickConfigModel))
     (vendor/heimrichhannot/contao-slick/classes/Hooks.php:28)
`

**Comment by fatcrobat** [comment]
Contao 4 File->mtime prüft nicht ob die Datei existiert, das war bei Contao 3 anders. Wir haben eine Überprüfung eingebaut, und sollte es nicht möglich sein ins Dateisystem zu schreiben, so wird im Contao-Log eine Meldung ausgegegen. Behoben in 1.4.4
