### ISSUE TITLE
Slick Konfiguration - can't add responsive slick_breakpoint 

### ISSUE THREAD

**Issue by sebssch** [heimrichhannot/contao-slick#22]
Es lassen sich keine weitere repsonsive Breakpoints  hinzufügen.
Nach einem klick auf das grüne Plus, lädt die Seite neu und nichts ist passiert.
- kein Fehler in der Console oder sonst irgendwo
- Contao 4.7

![slick konfiguration konfiguration id 4 bearbeiten - contao open source cms 2017-11-07 16-57-33](https://user-images.githubusercontent.com/18069290/32503202-f26139de-c3dc-11e7-898b-ceda9132aec5.png)

**Comment by Defcon0** [comment]
Das war ein Problem mit `heimrichhannot/contao-multi_column_editor` . Bitte update `contao-slick` auf `1.4.13`. Damit erhältst du auch die letzte Version von `contao-multi_column_editor`.

Damit sollte es wieder laufen. Eine Rückmeldung wäre super.

**Comment by sebssch** [comment]
Danke für die schnelle Antwort!
Funktioniert nachdem ich den Cache geleert hab 👍

**Comment by Defcon0** [comment]
Ja, hätte ich vielleicht dazuschreiben sollen ;-)

**Comment by hendrikbengs** [comment]
Bei mir tritt dasselbe Problem auf trotz aktuellster Version und geleertem Cache.

Contao 4.5.6
Contao-Slick: 1.6.0
