### ISSUE TITLE
Package heimrichhannot/contao-ajax is abandoned, what to do?

### ISSUE THREAD

**Issue by Shoekrates** [heimrichhannot/contao-slick#26]
Hi,
updating packages via Contao-Manager in Contao 4.4 brings up warnings:

```
<warning>Package heimrichhannot/contao-request is abandoned, you should avoid using it. Use heimrichhannot/contao-request-bundle instead.</warning> 
<warning>Package heimrichhannot/contao-ajax is abandoned, you should avoid using it. Use heimrichhannot/contao-ajax-bundle instead.</warning>  
```

What to do now? These are dependencies of „heimrichhannot/contao-multi_column_editor“ which is a dependency to „heimrichhannot/contao-slick“.

**Comment by fatcrobat** [comment]
We currently develop `https://github.com/heimrichhannot/contao-slick-bundle/` which will than, when ready, have no more ajax nor request dependency.
