### ISSUE TITLE
Headline-Field is not displayed

### ISSUE THREAD

**Issue by rustykowski** [heimrichhannot/contao-slick#27]
Contao 4.4.18, contao-slick 1.6.1:
The content-element Slick Image Slider does not show the standard field Headline.
If there is a headline stored in the database, it is not possible to modify. 
It is not an issue of field-settings in user-groups, because it also occurs for admin-users.
![bildschirmfoto 2018-04-27 um 10 06 48](https://user-images.githubusercontent.com/1775048/39351860-2717469e-4a03-11e8-8c1a-fcc0513aed19.png)

**Comment by fatcrobat** [comment]
Sorry for long delay, we currently drop module support and move our extensions to symfony bundles. Should be fixed in 1.6.3.
