### ISSUE TITLE
Can't create more than one breakpoints

### ISSUE THREAD

**Issue by Philipp96** [heimrichhannot/contao-slick#28]
If I want add create more than one breakpoints, I get the following error.

Contao 4.5.8
Contao Slick Slider v1.6.1

![slick-slider-fehlermeldung-breakpoints](https://user-images.githubusercontent.com/16081901/40168973-2be7a12e-59c5-11e8-9afc-61399cb6ffcb.png)

**Comment by koertho** [comment]
There is the jQuery component missing. Did you active it in your Layout?
But for contao 4 we created a bundle for slick slider, please use this instead: [https://github.com/heimrichhannot/contao-slick-bundle](https://github.com/heimrichhannot/contao-slick-bundle)
