### ISSUE TITLE
Can't install via composer

### ISSUE THREAD

**Issue by design23** [heimrichhannot/contao-slick#3]
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for heimrichhannot/contao-slick >=1.0.3.0,<1.1-dev -> satisfiable by heimrichhannot/contao-slick[1.0.3].
    - heimrichhannot/contao-slick 1.0.3 requires contao-legacy/multicolumnwizard >=3.2,,<4-dev -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion for more details.

Read http://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

**Comment by fatcrobat** [comment]
typo in composer.json for multicolumnwizard, fixed right now in 1.0.4
