### ISSUE TITLE
warum wird contao-multi_column_editor required?

### ISSUE THREAD

**Issue by zonky2** [heimrichhannot/contao-slick#30]
https://github.com/heimrichhannot/contao-slick/blob/master/composer.json#L28

ich sehe nicht, dass dieser in der Eingabemaske von Slick verwendet wird...

siehe https://github.com/heimrichhannot/contao-multi_column_editor/issues/3

**Comment by fatcrobat** [comment]
Siehe meinen Kommentar in deinem PR https://github.com/heimrichhannot/contao-slick/pull/31
