### ISSUE TITLE
responsive slick-settings anlegen

### ISSUE THREAD

**Issue by tuxenberger** [heimrichhannot/contao-slick#33]
Hallo heimrichhannot,

könnt ihr da weiterhelfen:
https://community.contao.org/de/showthread.php?72014-Contao-4-heimrichhannot-slick-slider-responsive-slick-settings

Viele Grüße, Marcel

**Comment by fatcrobat** [comment]
@tuxenberger Bitte die Beschreibung inkl. Screenshot noch einmal hier posten, danke.
