### ISSUE TITLE
(Sub)palette "slick_eventlist" not found in table "tl_module"

### ISSUE THREAD

**Issue by janoschbatschi** [heimrichhannot/contao-slick#34]
Since the last update I get following error:

> 22:16:00 ERROR     [console] Error thrown while running command "cache:warmup --env=prod". Message: "(Sub)palette "slick_eventlist" not found in table "tl_module"" ["error" => InvalidArgumentException { …},"command" => "cache:warmup --env=prod","message" => "(Sub)palette "slick_eventlist" not found in table "tl_module""] []
> 
> In PaletteManipulator.php line 211:
>                                                                  
>   (Sub)palette "slick_eventlist" not found in table "tl_module"

Can't open front- / backend or install page.

**Comment by koertho** [comment]
Since you seem to use Contao 4, please use the https://github.com/heimrichhannot/contao-slick-bundle.
If the error still occurs or you got the extension by installing another extension, please provide more information.
