### ISSUE TITLE
Meta information for Contao Manager

### ISSUE THREAD

**Issue by MDevster** [heimrichhannot/contao-slick#35]
First of all thank you for providing your extension(s). To take the quality of the Contao extensions to a new level, it would be nice if you could enrich your extensions with meta information and a logo for the Contao Manager. You can find out how to do this here: https://github.com/contao/package-metadata/tree/master/docs/en

Thanks in advance
Mathias

**Comment by fatcrobat** [comment]
@MDevster This module is abandoned as we already provide a symfony bundle that works with contao 4: https://github.com/heimrichhannot/contao-slick-bundle

**Comment by MDevster** [comment]
Thank you for your answer, I also meant it more generally for all your extensions. Respectively, it would be nice if you would deposit a general logo for the extensions.
