### ISSUE TITLE
jQuery.Deferred exception: Cannot read property 'x' of undefined TypeError: Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by mr2017x** [heimrichhannot/contao-slick#36]
Hi Guys,

i get the following error using your module with Contao 4.6.

may it's a cheap trick to get it running?

jQuery.Deferred exception: Cannot read property 'x' of undefined TypeError: Cannot read property 'x' of undefined

Thank you!

**Comment by koertho** [comment]
Hi. this module is outdated. Please use https://github.com/heimrichhannot/contao-slick-bundle or https://github.com/heimrichhannot/contao-tiny-slider-bundle.
