### ISSUE TITLE
InsertTags werden nicht ersetzt

### ISSUE THREAD

**Issue by akroii** [heimrichhannot/contao-slick#37]
Ist es möglich in den Feldern nextArrow und prevArrow InsertTags einzugeben, so dass diese im Frontend ersetzt werden? Bisher werden diese klartext ausgegeben.

![Bildschirmfoto 2019-06-25 um 16 40 06](https://user-images.githubusercontent.com/8830861/60107860-ecb19f00-9767-11e9-8e75-c4f5fd5eb3d6.png)

Slick: Version 1.6.4
Contao: 4.4.40

**Comment by Defcon0** [comment]
Bitte nutze slick-bundle für Contao 4:

https://github.com/heimrichhannot/contao-slick-bundle

**Comment by akroii** [comment]
Das Bundle ist noch nicht stabil.
![Bildschirmfoto 2019-06-26 um 09 01 42](https://user-images.githubusercontent.com/8830861/60158269-08ad5300-97f1-11e9-920e-1e1f3c181578.png)
