### ISSUE TITLE
Infinite-Modus / Klasse slick-current

### ISSUE THREAD

**Issue by birdmedia** [heimrichhannot/contao-slick#38]
Im Infinite-Modus scheint die Klasse "slick-current" nach dem Durchlauf der originären Inhalte verzögert gesetzt zu werden, was bei CSS-Animationen zu einem "Abriss" bzw. zu einer Verzögerung der Animation führt. Lässt sich das Problem beheben?

**Comment by koertho** [comment]
Wir pflegen dieses Modul nicht mehr, aber du darfst gern einen Pull-Request machen. Die slick-current Klasse wird aber von der Slick-Library gesetzt, da dürfte uns bundle keinen Einfluss haben. Falls du zur Library support brauchst, bitte direkt dort fragen.
