### ISSUE TITLE
Fade instead of Crossfade

### ISSUE THREAD

**Issue by pixelmatty** [heimrichhannot/contao-slick#39]
Dear Community

I'm using slick slider (contao extension) because I like the fading option that was not available at former standard sliders. For fading slides slick uses crossfade mode: one slide removes while at the same time the next arrives. 
So if I want to slide pictures that are mainly identical but only parts of it change, the change causes a flicker (from background). Instead this the fading should blend the next slide over the 100% previous and remove the previous only after finishing. So it looks like the picture dosn't change (except the parts).
Can I change the fade mode to this in slick configuration or build a variation to select? If yes how?

Thanks in advance for information
Pixelmatty

**Comment by koertho** [comment]
Hi, first of all: this bundle is outdated: for usage with contao 4 you should use https://github.com/heimrichhannot/contao-slick-bundle. 

You can check which options are available in the contao backend: https://github.com/heimrichhannot/contao-slick-bundle#setup

If it is not available there, you could use the javascript event to modify the the slick config: https://github.com/heimrichhannot/contao-slick-bundle/blob/master/docs/developers.md#js-events

**Comment by pixelmatty** [comment]
Hi koertho

Thanks for quick reply. Sorry, yes I use the actual Slick Bundle. 
In backend mask only ease options are available (this works für the single image not the blending from prev to next). The blending technique (fade) should be modified. I can only choose yes or no.
I'm afraid I don't know where to start with javascript events because I'm designer, coding is not my profession.

Any suggestion at this circumstances? ;-)
Regards
Pixelmatty

**Comment by koertho** [comment]
Yes/no are the available parameters for the library, see http://kenwheeler.github.io/slick/#:~:text=Enable%20mouse%20dragging-,fade,-boolean

I don't know if slick allows something other. This extension is only a bridge between the js library (which we didn't developed) and contao. We also not actively developing slick bundle anymore (see notice at the readme at https://github.com/heimrichhannot/contao-slick-bundle). You can also try our tiny slider bundle if it fullfills your need: https://github.com/heimrichhannot/contao-tiny-slider-bundle (but there also: we just developed the contao integration, not the library)

To start with javascript, a tutorial could be a good start ;) for example https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Events

**Comment by pixelmatty** [comment]
OK, thanks. For this time no chance. ;-)
Exemple for understanding: fritzmg made the swiper extension (for contao, but this is only a simple slider). It replaces the standard slider and has in the backend window the selection of 'crossfade' and 'fade' (with exaxt the difference that i mentioned).
