### ISSUE TITLE
Not working in Contao 3.5.0

### ISSUE THREAD

**Issue by akroii** [heimrichhannot/contao-slick#4]
Please add an installation-Guide...
Does it run  under Contao 3.5.0?

The variable in jquery.slick.html5 (should named into j_slick.html5?) `<?php echo $this->config;?>` is NULL

**Comment by fatcrobat** [comment]
Did you create an slick config in the backend? Under System - Slickconfig?

**Comment by fatcrobat** [comment]
And select the config in your slider content/module/news archive.

**Comment by akroii** [comment]
yes, i add an config and select it in the content-element

**Comment by akroii** [comment]
it is necessary to install the extension via composer?
I have installed it manually.
The multicolumnwizard Versino is 3.3.3

**Comment by rflx** [comment]
Agree that the `content-slider` is not working under Contao 3.5.0. 
On the other side the `image-slider` is working.

@akroii Your configuration will directly executed after the slick.js in your JavaScript collection.

**Comment by fatcrobat** [comment]
@akroii Please check again with the latest version `1.0.13`. Tried with fresh contao 3.5.0 setup and after that fix `content slider` is working. Be sure to activate jquery in your page layout as long it is required by slick. 

And yes, i recommend to install via composer as long as all dependencies will be solved like magic. 
Manual contao module installations is not recommented.
