### ISSUE TITLE
Contao Slick Bundle with thumbnails

### ISSUE THREAD

**Issue by pixelmatty** [heimrichhannot/contao-slick#40]
Dear community

I use latest Contao 4.9 with latest Slick Bundle. Has anyone already used it with one image and below (or beside) the thumbnails of all pictures of the slider and built a template for this? There are some general examples in the web (e.g. via code pen) but I'm not able to transform this for use with the Contao Slick extension. I suppose a template and some formatting css for extra selectors are the way?

I would appreciate some help.
Thanks
Pixelmatty

**Comment by koertho** [comment]
Please always post issues in the right repo. I don't really know what you mean. Maybe you can open the issue in the slick bundle repo and post an example there, that you mentioned.

**Comment by pixelmatty** [comment]
OK, sorry, I didn't realize that there is a different repo for the bundle.
