### ISSUE TITLE
PHP 8.1 Support

### ISSUE THREAD

**Issue by hinzke** [heimrichhannot/contao-slick#41]
Will there be an update for PHP 8.1 support?

When switching to PHP 8.1 and updating all packages, the following message appears:
`heimrichhannot/contao-slick[1.6.0, ..., 1.6.4] require php ~5.4 || ~7.0 -> your php version (8.1.10.0) does not satisfy that requirement.`

**Comment by koertho** [comment]
> If you are on Contao 4, please use https://github.com/heimrichhannot/contao-slick-bundle or https://github.com/heimrichhannot/contao-tiny-slider-bundle.

It already supports php 8
