### ISSUE TITLE
TypeError: Cannot read property 'length' of null

### ISSUE THREAD

**Issue by rflx** [heimrichhannot/contao-slick#5]
Hi,
just received this JavaScript error after updating to contao-slick 1.0.17:

```
TypeError: Cannot read property 'length' of null
```

inside the `Slick.prototype.destroy` function in slick.js:

``` javascript
if ( _.$prevArrow.length ) {

            _.$prevArrow
                .removeClass('slick-disabled slick-arrow slick-hidden')
                .removeAttr('aria-hidden aria-disabled tabindex')
                .css("display","");

            if ( _.htmlExpr.test( _.options.prevArrow )) {
                _.$prevArrow.remove();
            }
        }
```

Thx n' cheers
rflx

**Comment by rflx** [comment]
Me again, 
this problem occures only if `arrows = false` and if the `responsive` option is enabled i think.

check #1528 or #1536
https://github.com/kenwheeler/slick/issues/1528
https://github.com/kenwheeler/slick/issues/1536

Hotfix:
https://github.com/kenwheeler/slick/commit/4f8adffddb949cddb8a447f18dc3ccb182c7ac3e

Cheers

**Comment by rflx** [comment]
This issue should be fixed in the latest slick.js release (1.5.8). contao-slick is using slick.js 1.5.6 at the moment.

**Comment by fatcrobat** [comment]
thanks for your research, will fix this on monday. have a nice weekend!

**Comment by fatcrobat** [comment]
Updated slick.js library to version 1.5.8 in tag 1.0.18/master.

**Comment by rflx** [comment]
Thank you @fatcrobat – Have a nice evening! :sunglasses:
