### ISSUE TITLE
Wrong Class Name

### ISSUE THREAD

**Issue by christianromeni** [heimrichhannot/contao-slick#6]
Hi,
first of all, thank you for slick, I did not yet get it to work, but I eventually will...

I'm trying to get it to work for the News-List. And I noticed that therewas a problem with the class name.

```
slick_2f8da9 .slick-container
```

There is a dot that should not be there. I traced it to here: [SlickConfig.php#L60](https://github.com/heimrichhannot/contao-slick/blob/master/classes/SlickConfig.php#L60)

But I did not manage to remove the dot in my system.. Maybe I missed some other part where it could have been added.... Would be awesome if you could take a look.

**Comment by fatcrobat** [comment]
What slick version u are using?

**Comment by christianromeni** [comment]
1.0.18 installed via composer

**Comment by fatcrobat** [comment]
Can you pleas clear your assets/js folder? That issue should have been fixes recently. Did you update slick from an older version?

**Comment by christianromeni** [comment]
No, I installed it straight from composer and have not installed before.
Also I have cleared everything and neither system nor browser cache is enabled.

**Comment by fatcrobat** [comment]
Alright, fixed within [1.0.19](https://github.com/heimrichhannot/contao-slick/tree/1.0.19).
