### ISSUE TITLE
Throws error after contao/install.php

### ISSUE THREAD

**Issue by akroii** [heimrichhannot/contao-slick#9]
I want to update the database and go into contao/install.php.
Iam using 3.5.4. / contao-slick-1.0.19
Installed/downloaded manually via this repository (no composer)
Created "slick" folder in system/modules/

```
Warning: in_array() expects parameter 2 to be array, null given in C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\System.php on line 140
#0 [internal function]: __error(2, 'in_array() expe...', 'C:\\MAMP\\htdocs\\...', 140, Array)
#1 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\System.php(140): in_array('getInstance', NULL)
#2 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\slick\dca\tl_slick_spread.php(12): Contao\System->import('\\HeimrichHannot...')
#3 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\DcaLoader.php(86): include('C:\\MAMP\\htdocs\\...')
#4 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\Controller.php(1263): Contao\DcaLoader->load(false)
#5 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\DcaExtractor.php(382): Contao\Controller::loadDataContainer('tl_slick_spread')
#6 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\DcaExtractor.php(128): Contao\DcaExtractor->createExtract()
#7 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\DcaExtractor.php(144): Contao\DcaExtractor->__construct('tl_slick_spread')
#8 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\Database\Installer.php(295): Contao\DcaExtractor::getInstance('tl_slick_spread')
#9 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\Database\Installer.php(111): Contao\Database\Installer->getFromDca()
#10 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\Database\Installer.php(41): Contao\Database\Installer->compileCommands()
#11 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\controllers\BackendInstall.php(633): Contao\Database\Installer->generateSqlForm()
#12 C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\controllers\BackendInstall.php(177): Contao\BackendInstall->adjustDatabaseTables()
#13 C:\MAMP\htdocs\yyy\contao-3.5.0\contao\install.php(24): Contao\BackendInstall->run()
#14 {main}

Fatal error: Class '\HeimrichHannot\Slick\Constants' not found in C:\MAMP\htdocs\yyy\contao-3.5.0\system\modules\core\library\Contao\System.php on line 140
```

**Comment by akroii** [comment]
update;
if you want to update the database try to go in to the contao backend -> extensions -> update database
works

but no scripts included?! jquery.slick.html5 did not included and not visible in layouts

**Comment by fatcrobat** [comment]
That error might occur due to active internal cache in contao setting if you did not install via composer. 

If it is working now, that might have been the reason. Can you confirm that?

**Comment by akroii** [comment]
i can confirm that.
another issue i have is the missing jquery files (jquery.slick.html5) does not included.

**Comment by fatcrobat** [comment]
Clear your assets/js folder via contao maintenance.

**Comment by akroii** [comment]
Now i get the slick.js included. But the js plugin does not.
in `assets/js/` there is a empty `slick_2f8da9.js` file?

**Comment by fatcrobat** [comment]
Have you created a slick configuration in the backend and attached it to your slider?

**Comment by akroii** [comment]
yes, a configuration in "System -> Slick Configuration" is setted and attached to my slider

**Comment by fatcrobat** [comment]
Deleting slick_2f8da9.js file will recreate that file. Tried that already?

**Comment by akroii** [comment]
yes. no luck. same file with no input

**Comment by fatcrobat** [comment]
Slick requires matthiasmullie/minify. Is that available in your vendor folder (vendor/matthiasmullie)? Composer install that plugin automatically.

**Comment by akroii** [comment]
is availible

**Comment by fatcrobat** [comment]
Please try contao-slick 1.0.34, i added an check that will only minify if "\MatthiasMullie\Minify\JS" is available.

**Comment by akroii** [comment]
Downloaded the new version and installed via this repository.
slick.js and plugin js does not included and i have no in frontend output.

now, the file `slick_2f8da9.js` have content!

I got this in error.log
`[27-Nov-2015 15:10:35 Europe/Berlin] PHP Fatal error:  Class '\HeimrichHannot\Slick\Constants' not found in C:\xampp\htdocs\yyy\system\modules\core\library\Contao\System.php on line 140`

**Comment by fatcrobat** [comment]
Alright, i moved constants to config.php, try version 1.0.35.

**Comment by akroii** [comment]
same issue.. its like a ghost in frontend. no scripts included.

**Comment by fatcrobat** [comment]
You still get the 'PHP Fatal error: Class '\HeimrichHannot\Slick\Constants'" Error'?
Cleared you assets/js folder again?

**Comment by akroii** [comment]
i dont get this first php error again
assets/js is already cleared

**Comment by akroii** [comment]
I've upgraded all extensions with composer.
Same problem. No output

**Comment by fatcrobat** [comment]
Can you provide a copy of your environment?

**Comment by akroii** [comment]
Do you have a mail-adress or something?

**Comment by fatcrobat** [comment]
digitales@heimrich-hannot.de

**Comment by akroii** [comment]
UPDATE:
1. install composer and update all plugins (it is not possible to keep it running without composer)
2. checkbox "Bypass the internal cache"
3. clear assets/css & js
4. should run now

**Comment by fatcrobat** [comment]
Thanks for posting the solution.
